apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhacs-ir-rbac.yaml
  - rhacs-ir-publish-rbac.yaml
  - kube-apiserver-checkpoints.yaml
  - rhacs-ir-checkpoint-fetch-scc.yaml
